name: Empaquetado
on:
  workflow_dispatch:
    inputs:
      modulo:
        required: true
        type: choice
        options:
          - frontend
          - backend
          - data
          - full
jobs:
  empaquetado:
    runs-on: ubuntu-latest
    steps:
    - name: artifact_frontend
      if: ${{ github.event.inputs.modulo == 'frontend' }}
      run: echo "fontend does brr seleccionado"
    - name: artifact_backend
      if: ${{ github.event.inputs.modulo == 'backend' }}
      run: echo "fontend does brr seleccionado"
    
    
