  name: Empaquetado
on:
  workflow_dispatch:
    inputs:
      modulo:
        required: true
        type: choice
        options:
          - frontend
          - backend
          - data
          - full
jobs:
  empaquetado:
    runs-on: ubuntu-latest
    steps:
    - name: artifact_frontend
      if: ${{ github.event.inputs.modulo == 'frontend' }}
      run: zip -r frontend.zip templates
    - name: artifact_backend
      if: ${{ github.event.inputs.modulo == 'backend' }}
      run: zip -r backend.zip app.py
    - name: artifact_data
      if: ${{ github.event.inputs.modulo == 'data' }}
      run: zip -r data.zip data
    - name: artifact_full
      if: ${{ github.event.inputs.modulo == 'full' }}
      run: zip -r full.zip
      
    - name: create_artifact
      uses: actions/upload-artifact@v4
      with:
          name: ${{ github.event.inputs.module }}-package
          path: "*.zip"
