name: Python Coverage
on:
    pull_request:
        branches:
            - main
permissions:
  pull-requests: write

jobs:
  python-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.13
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify structue
        run: |
            if [ ! -f app.py ]; then exit 1; fi
            if [ ! -f requirements.txt ]; then exit 1; fi
            if [ ! -d templates ]; then exit 1; fi
            if [ ! -d static ]; then exit 1; fi
            if [ ! -d data ]; then exit 1; fi

      - name: Validate json files
        run: |
            if [ ! -f data/users.json ]; then exit 1; fi
            python -m json.tool data/users.json > /dev/null
            if [ ! -f data/events.json ]; then exit 1; fi
            python -m json.tool data/events.json > /dev/null
            if [ ! -f data/orders.json ]; then exit 1; fi
            python -m json.tool data/orders.json > /dev/null
            
